twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        functions: '@App\Services\Functions'
        trackerCache: '@App\Services\TrackerMemcached'
    paths:
        '%kernel.project_dir%/assets/email': images